name: "Analyze Before Deploy"
description: "Uploads the repository as a zip file to an analysis app, checks the result, and either proceeds or blocks the deployment."

author: "fady"
inputs:
  analysis_url:
    description: "The URL of the analysis backend"
    required: true

outputs:
  result:
    description: "The result of the analysis (pass or fail)"

runs:
  using: "composite"
  steps:
    - name: Zip the repository
      run: zip -r repo.zip .
      shell: bash

    - name: Upload the zip file to the analysis app and handle result
      run: |
        ANALYSIS_RESULT=$(curl -s -X POST "${{ inputs.analysis_url }}" \
          -F "file=@repo.zip" \
          | jq -r '.status')
        echo "Analysis result: $ANALYSIS_RESULT"
        echo "::set-output name=result::$ANALYSIS_RESULT"
        if [[ "$ANALYSIS_RESULT" == "fail" ]]; then
          echo "Deployment blocked: Analysis failed."
          exit 1  # Fail the action
        fi
      shell: bash
